<?php
declare(strict_types=1);

function monthly_goal(string $month,int $year): ?array
{
    $stmt=db()->prepare('SELECT * FROM metas_mensais WHERE mes=? AND ano=?');$stmt->execute([$month,$year]);$goal=$stmt->fetch();if(!$goal)return null;$individual=db()->prepare('SELECT mi.*,u.nome user_nome,u.email user_email FROM metas_individuais mi JOIN users u ON u.id=mi.user_id WHERE mi.meta_mensal_id=?');$individual->execute([$goal['id']]);$goal['metas_individuais']=$individual->fetchAll();return $goal;
}

function individual_report(int $userId,string $month,int $year): array
{
    $meta=db()->prepare('SELECT mi.meta_quantidade FROM metas_individuais mi JOIN metas_mensais mm ON mm.id=mi.meta_mensal_id WHERE mi.user_id=? AND mm.mes=? AND mm.ano=?');$meta->execute([$userId,$month,$year]);$target=(int)($meta->fetchColumn()?:0);$count=db()->prepare('SELECT COUNT(*) FROM escrituras e JOIN users u ON u.id=? WHERE (e.created_by=u.id OR (e.created_by IS NULL AND LOWER(TRIM(e.escrevente))=LOWER(TRIM(u.nome)))) AND e.mes=? AND e.ano=? AND e.archived_at IS NULL');$count->execute([$userId,$month,$year]);$production=(int)$count->fetchColumn();$previousMonth=$month==='01'?'12':str_pad((string)((int)$month-1),2,'0',STR_PAD_LEFT);$previousYear=$month==='01'?$year-1:$year;$count->execute([$userId,$previousMonth,$previousYear]);$previous=(int)$count->fetchColumn();$percentage=$target>0?$production/$target*100:0;$variation=$previous>0?($production-$previous)/$previous*100:0;return['userId'=>$userId,'mes'=>$month,'ano'=>$year,'meta'=>$target,'producao'=>$production,'percentual'=>round($percentage,1),'status'=>$percentage>=100?'superou':($percentage>=80?'atingiu':'abaixo'),'producaoAnterior'=>$previous,'variacao'=>round($variation,1)];
}

function team_report(string $month,int $year): array
{
    $goal=monthly_goal($month,$year);$count=db()->prepare('SELECT COUNT(*) FROM escrituras WHERE mes=? AND ano=?');$count->execute([$month,$year]);$production=(int)$count->fetchColumn();$target=(int)($goal['meta_total']??0);$users=(int)db()->query('SELECT COUNT(*) FROM users WHERE ativo=1')->fetchColumn();$group=function(string $column,string $label)use($month,$year){$stmt=db()->prepare("SELECT $column $label,COUNT(*) quantidade FROM escrituras WHERE mes=? AND ano=? GROUP BY $column ORDER BY quantidade DESC");$stmt->execute([$month,$year]);return$stmt->fetchAll();};$previousMonth=$month==='01'?'12':str_pad((string)((int)$month-1),2,'0',STR_PAD_LEFT);$previousYear=$month==='01'?$year-1:$year;$count->execute([$previousMonth,$previousYear]);$previous=(int)$count->fetchColumn();$percentage=$target>0?$production/$target*100:0;return['mes'=>$month,'ano'=>$year,'meta'=>$target,'producao'=>$production,'percentual'=>round($percentage,1),'status'=>$percentage>=100?'superou':($percentage>=80?'atingiu':'abaixo'),'mediaPorPessoa'=>round($users>0?$production/$users:0,1),'distribuicaoPorTipo'=>$group('tipo','tipo'),'distribuicaoPorEscrevente'=>$group('escrevente','escrevente'),'producaoAnterior'=>$previous,'variacao'=>round($previous>0?($production-$previous)/$previous*100:0,1)];
}

function handle_goals(string $method,array $parts): never
{
    require_role('visualizador');
    if($method==='POST'&&count($parts)===1){require_role('admin');$data=body();$month=str_pad((string)($data['mes']??''),2,'0',STR_PAD_LEFT);$year=(int)($data['ano']??0);$total=(int)($data['metaTotal']??0);if(!$year||!$total)fail('Mes, ano e meta total sao obrigatorios');with_transaction(function(PDO $pdo)use($month,$year,$total,$data){$stmt=$pdo->prepare('SELECT id FROM metas_mensais WHERE mes=? AND ano=? FOR UPDATE');$stmt->execute([$month,$year]);$id=$stmt->fetchColumn();if($id){$pdo->prepare('UPDATE metas_mensais SET meta_total=? WHERE id=?')->execute([$total,$id]);$pdo->prepare('DELETE FROM metas_individuais WHERE meta_mensal_id=?')->execute([$id]);}else{$pdo->prepare('INSERT INTO metas_mensais(mes,ano,meta_total)VALUES(?,?,?)')->execute([$month,$year,$total]);$id=$pdo->lastInsertId();}$insert=$pdo->prepare('INSERT INTO metas_individuais(meta_mensal_id,user_id,meta_quantidade)VALUES(?,?,?)');foreach(($data['metasIndividuais']??[])as$item)$insert->execute([$id,$item['userId'],$item['quantidade']]);});audit('SET_GOAL','metas_mensais',null,null,['mes'=>$month,'ano'=>$year,'metaTotal'=>$total]);json_response(monthly_goal($month,$year));}
    if($method==='GET'&&($parts[1]??null)==='relatorio'&&($parts[2]??null)==='individual')json_response(individual_report((int)$parts[3],str_pad((string)$parts[4],2,'0',STR_PAD_LEFT),(int)$parts[5]));
    if($method==='GET'&&($parts[1]??null)==='relatorio'&&($parts[2]??null)==='equipe')json_response(team_report(str_pad((string)$parts[3],2,'0',STR_PAD_LEFT),(int)$parts[4]));
    if($method==='GET'&&($parts[1]??null)==='ranking'){$month=str_pad((string)$parts[2],2,'0',STR_PAD_LEFT);$year=(int)$parts[3];$stmt=db()->prepare('SELECT u.id,u.nome,u.email,COUNT(e.id) producao,mi.meta_quantidade meta FROM users u LEFT JOIN escrituras e ON (e.created_by=u.id OR (e.created_by IS NULL AND LOWER(TRIM(e.escrevente))=LOWER(TRIM(u.nome)))) AND e.mes=? AND e.ano=? AND e.archived_at IS NULL LEFT JOIN metas_mensais mm ON mm.mes=? AND mm.ano=? LEFT JOIN metas_individuais mi ON mi.user_id=u.id AND mi.meta_mensal_id=mm.id WHERE u.ativo=1 GROUP BY u.id,u.nome,u.email,mi.meta_quantidade ORDER BY producao DESC');$stmt->execute([$month,$year,$month,$year]);$rows=$stmt->fetchAll();foreach($rows as &$row)$row['percentual']=($row['meta']??0)>0?round($row['producao']/$row['meta']*100,1):0;json_response($rows);}
    if($method==='GET'&&($parts[1]??null)==='projecao'){$month=str_pad((string)$parts[2],2,'0',STR_PAD_LEFT);$year=(int)$parts[3];if($month!==date('m')||$year!==(int)date('Y'))json_response(null);$stmt=db()->prepare('SELECT COUNT(*) FROM escrituras WHERE mes=? AND ano=?');$stmt->execute([$month,$year]);$current=(int)$stmt->fetchColumn();$day=(int)date('j');$days=(int)date('t');json_response(['diaAtual'=>$day,'diasNoMes'=>$days,'producaoAtual'=>$current,'projecaoFimMes'=>$day>0?(int)round($current/$day*$days):0]);}
    if($method==='GET'&&isset($parts[1],$parts[2])){$goal=monthly_goal(str_pad((string)$parts[1],2,'0',STR_PAD_LEFT),(int)$parts[2]);if(!$goal)fail('Meta nao encontrada',404);json_response($goal);}fail('Rota nao encontrada',404);
}

